### ISSUE TITLE
Connection Failure

### ISSUE THREAD

**Issue by Wilhelm1Daniel** [mainde/klipper-moonraker-tapo#3]
Hi,

I use the P110 plug and tried it with your code...
When I'll tried to start the service it won't be start.

Here ist the protocol...

Nov 05 11:10:22 raspberrypi systemd[1]: Starting Tapo HTTP server...
Nov 05 11:10:22 raspberrypi systemd[6395]: tapo.service: Failed to determine user credentials: No such process
Nov 05 11:10:22 raspberrypi systemd[6395]: tapo.service: Failed at step USER spawning /bin/sleep: No such process
Nov 05 11:10:22 raspberrypi systemd[1]: tapo.service: Control process exited, code=exited, status=217/USER
Nov 05 11:10:22 raspberrypi systemd[1]: tapo.service: Failed with result 'exit-code'.
Nov 05 11:10:22 raspberrypi systemd[1]: Failed to start Tapo HTTP server.
Nov 05 11:10:22 raspberrypi systemd[1]: tapo.service: Scheduled restart job, restart counter is at 1.
Nov 05 11:10:22 raspberrypi systemd[1]: Stopped Tapo HTTP server.
Nov 05 11:10:22 raspberrypi systemd[1]: Starting Tapo HTTP server...
Nov 05 11:10:22 raspberrypi systemd[1]: tapo.service: Control process exited, code=exited, status=217/USER
Nov 05 11:10:22 raspberrypi systemd[1]: tapo.service: Failed with result 'exit-code'.
Nov 05 11:10:22 raspberrypi systemd[1]: Failed to start Tapo HTTP server.
Nov 05 11:10:22 raspberrypi systemd[1]: tapo.service: Scheduled restart job, restart counter is at 2.
Nov 05 11:10:22 raspberrypi systemd[1]: Stopped Tapo HTTP server.
Nov 05 11:10:22 raspberrypi systemd[1]: Starting Tapo HTTP server...
Nov 05 11:10:22 raspberrypi systemd[1]: tapo.service: Control process exited, code=exited, status=217/USER
Nov 05 11:10:22 raspberrypi systemd[1]: tapo.service: Failed with result 'exit-code'.
Nov 05 11:10:22 raspberrypi systemd[1]: Failed to start Tapo HTTP server.
Nov 05 11:10:22 raspberrypi systemd[1]: tapo.service: Scheduled restart job, restart counter is at 3.
Nov 05 11:10:22 raspberrypi systemd[1]: Stopped Tapo HTTP server.
Nov 05 11:10:23 raspberrypi systemd[1]: Starting Tapo HTTP server...
Nov 05 11:10:23 raspberrypi systemd[1]: tapo.service: Control process exited, code=exited, status=217/USER
Nov 05 11:10:23 raspberrypi systemd[1]: tapo.service: Failed with result 'exit-code'.
Nov 05 11:10:23 raspberrypi systemd[1]: Failed to start Tapo HTTP server.
Nov 05 11:10:23 raspberrypi systemd[1]: tapo.service: Scheduled restart job, restart counter is at 4.
Nov 05 11:10:23 raspberrypi systemd[1]: Stopped Tapo HTTP server.
Nov 05 11:10:23 raspberrypi systemd[1]: Starting Tapo HTTP server...
Nov 05 11:10:23 raspberrypi systemd[1]: tapo.service: Control process exited, code=exited, status=217/USER
Nov 05 11:10:23 raspberrypi systemd[1]: tapo.service: Failed with result 'exit-code'.
Nov 05 11:10:23 raspberrypi systemd[1]: Failed to start Tapo HTTP server.
Nov 05 11:10:23 raspberrypi systemd[1]: tapo.service: Scheduled restart job, restart counter is at 5.
Nov 05 11:10:23 raspberrypi systemd[1]: Stopped Tapo HTTP server.
Nov 05 11:10:23 raspberrypi systemd[1]: tapo.service: Start request repeated too quickly.
Nov 05 11:10:23 raspberrypi systemd[1]: tapo.service: Failed with result 'exit-code'.
Nov 05 11:10:23 raspberrypi systemd[1]: Failed to start Tapo HTTP server.

**Comment by mainde** [comment]
Hiya, I'm not really sure to be honest, but a couple of things stand out in your error log. Searching for this line:
> Failed to determine user credentials: No such process

I found a few possible solutions: https://superuser.com/questions/1156676/what-causes-systemd-failed-at-step-user-spawning-usr-sbin-opendkim-no-such-p

Have you by any chance changed the default user `pi` on your system? The `Service` section in `/etc/systemd/system/tapo.service` calls out User and Group, if on your system those are not `pi` then maybe that's the issue, you need to update those lines to match the user you are using. 🙂 

Alternatively, it may mean that you need to reboot/restart systemd, rebooting the pi or doing `systemctl daemon-reexec`.

**Comment by mainde** [comment]
@Wilhelm1Daniel have you sorted this out?
