### ISSUE TITLE
I'm not able to get the Power On Button on Dashboard

### ISSUE THREAD

**Issue by Mysteoa** [mainde/klipper-moonraker-tapo#4]
Hi,

I had previously used your guide to make my Tapo P100 to work, and I did get the Power On button on the Dashboard to show.
But unfortunately, my SD card died without me making a BKP of my config.

I have remade it again and the dropdown menu button works fine. But I want to get the Power On button under "To power on the printer, click the button below" msg to show on the Dashboard like before. The same one I see in your gif. I have been trying for some time, but I can't figure it out. Has something changed in Klipper/Moonraker that is preventing this?

This is in my moonraker.cfg 

[power Printer TapoP100]
type: http
on_url: http://localhost:56427/on
off_url: http://localhost:56427/off
status_url: http://localhost:56427/
off_when_shutdown: True
restart_klipper_when_powered: true
initial_state: off
locked_while_printing: True
on_when_job_queued: True
bound_services: klipper
response_template:
  {% set resp = http_request.last_response().json() %}
  {% if resp["device_on"] %}
    {"on"}
  {% else %}
    {"off"}
  {% endif %}
  
 Everything else is the same, only PyP110 was switched to PyP100 in the script.

**Comment by mainde** [comment]
mmmh, I think "Printer" needs to be lowercase "printer" in that first line you pasted

I'm not 100% sure because I haven't touched this in a few months, but I think that may be it

**Comment by Mysteoa** [comment]
I tryed lower case, even removing the word and only leaving "tapo100". Still the same.

**Comment by mainde** [comment]
ah yes, it should only say "[power printer]", nothing else
it comes from here: https://docs.mainsail.xyz/overview/quicktips/printer-power-switch
>Important is the name printer and the attribute bound_services: klipper. Mainsail will use this power device to check for a "powered off" printer.

the documentation of mainsail hasn't changed so I think the config should still be valid 🤔 

the only other reason I can think of for the button not showing is that the status returned by "http://localhost:56427/" isn't correct? and mainsail thinks the printer is already on? but if the dropdown button works then that's not the case 🤔

**Comment by Mysteoa** [comment]
Yes, it did work with just "printer". I don't know how I missed that line, but it is probably because I was thinking the problem was elsewhere.
